### ISSUE TITLE
Figure out how we will implement a second API

### ISSUE THREAD

**Issue by tguy5837** [annoyingdroid/FoodyTrack#16]
- We could do a nutrition page where an extensive list of nutrition info is displayed
OR
- Figure out how we could search for ingredients in stores near us
OR
- Something else

**Comment by annoyingdroid** [comment]
I would say lets go ahead and implement the second API to pull up more nutrition information. I hadn't seen anything in the API list for looking up ingredient locations. Plus, it would be more in line with the whole nutrition thing we have been going for
